"""autogenerated by genpy from OpenTLD/Dest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Dest(genpy.Message):
  _md5sum = "a5105e66da1cec3d8307f13104ccec1b"
  _type = "OpenTLD/Dest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Destination Tracking

#True: Destination Present in Frame #False: Destination absent
bool destPresent

#Destination rectangle is given by (x,y) and (x+w, y+h)
int32 destX
int32 destY
int32 destWidth
int32 destHeight

"""
  __slots__ = ['destPresent','destX','destY','destWidth','destHeight']
  _slot_types = ['bool','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       destPresent,destX,destY,destWidth,destHeight

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Dest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.destPresent is None:
        self.destPresent = False
      if self.destX is None:
        self.destX = 0
      if self.destY is None:
        self.destY = 0
      if self.destWidth is None:
        self.destWidth = 0
      if self.destHeight is None:
        self.destHeight = 0
    else:
      self.destPresent = False
      self.destX = 0
      self.destY = 0
      self.destWidth = 0
      self.destHeight = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B4i.pack(_x.destPresent, _x.destX, _x.destY, _x.destWidth, _x.destHeight))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.destPresent, _x.destX, _x.destY, _x.destWidth, _x.destHeight,) = _struct_B4i.unpack(str[start:end])
      self.destPresent = bool(self.destPresent)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B4i.pack(_x.destPresent, _x.destX, _x.destY, _x.destWidth, _x.destHeight))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.destPresent, _x.destX, _x.destY, _x.destWidth, _x.destHeight,) = _struct_B4i.unpack(str[start:end])
      self.destPresent = bool(self.destPresent)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B4i = struct.Struct("<B4i")
